format = """
$env_var\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$ruby
$character"""

[ruby]
symbol = '🔺 '

[git_status]
conflicted = ''
ahead = '⇡'
behind = '⇣'
diverged = ''
up_to_date = '✓'
untracked = ''
stashed = '📦'
modified = ''
staged = '+'
renamed = ''
deleted = ''

[directory]
truncation_length = 8
truncation_symbol = ''

[env_var.SPIN]
format = "[꩜ ]($style) "
style = "fg:33"

[git_metrics]
added_style = 'bold blue'
deleted_style = 'red'
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '
disabled = false 
